question_list = [""" Namaskar, Deviyo or Sajjano. \nI Vinod Rathore, Welcomes all of you in this game. Firstly, I am making aware you about the rule of the game"\n\n\t\t::::::::::::: Rules :::::::::::::\n\n\t # You should reply your answer either 'A/B/C/D' or 'a/b/c/d', No other answer will be acceptable.\n\t # If you will misbehave then I shall terminate the game anytime. \n\t #You have 2 lifeline :\n\t\t 1. Double Dip : For this you need to type 'dd' or 'DD' \n\t\t 2. Fifty-Fifty(50-50) : For this you need to type 'ff' or 'FF'. \n\t * If you use double dip then you are eligible to answer two times and if you use 50-50, we will remove two answers from the option. \n\t * You are eligible to use lifeline only if you will reach on 1st stage.\n\n :::::::::::::  Hope, you will enjoy the Game :::::::::::::""", "\nFirst question for Rs. 10000 is : \n\n1. Which of these words means 'revolution' in Arabic?",  "Second question for Rs. 20000 is : \n\n2. In cricket, which of these modes of dismissals always involves the wicket-keeper ?", "Third question for Rs. 40000 is : \n\n3. Which scientist has been named for the Bharat Ratna in 2013? ", "Fourth question for Rs. 80000 is : \n\n4. Which of these is the administrative head of a district in India ? ", "Fifth question for Rs. 160000 is : \n\n5. Which scholar started the Mohammedan Anglo Oriental College which later became the Aligarh Muslim University ? ", "Sixth question for Rs. 320000 is : \n\n6. Which is the oldest mountain range in India ?", "Seventh question for Rs. 640000 is : \n\n7. In October 2013, which actress was honored by the British House of Commons ?", "Eighth question for Rs. 1250000 is : \n\n8. What was the first Grand Slam tennis title won by Sania Mirza ?", "Ninth question for Rs. 2500000 is : \n\n9. Which ruler of the Delhi Sultanate was called 'Lakh Baksh' for his generosity ?", "Tenth question for Rs. 5000000 is : \n\n10. The president of which African country was conferred the Indira Gandhi Peace Prize in September 2013 ?", "Eleventh question for Rs. 10000000 is : \n\n11. Who is the first Indian Women to conquer the highest peak of all seven continent ?", "Twelfth question for Rs. 30000000 is : \n\n12. In Which theatre was 'Raja Harishchandra' , India's first feature film, commercially released 100 years ago on 3rd May ?", "This is the last question for Rs. 50000000 is : \n\n13. Who presented the National flag to the constituent Assembly on 14 August 1947 on behalf of the Women of India ?"]

option_list = ["\n:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::", "\tA. Isteqbaal\tB. Intikhaab\tC. Inquilab\tD. Intequam",  "\tA. LBW\tB. Caught and Bowled\tC. Run Out\tD. Stumping", "\tA. Prof C N R Rao\tB. Pro U R Rao\tC. Prof Yash Pal\tD. Dr K Radhakrishnan", "\tA. DM\tB. DCP\tC. DSP\tD. DIG", "\tA. Syed Ahmad Khan\tB. Muhammad Iqbal\tC. Maulana Mohomed Ali\tD. Dr Zakir Hussain", "\tA. Nilgiris \tB. Aravalli \tC. Vindhya \tD. Satpura", "\tA. Vidya Balan \tB. Madhuri Dixit \tC. Sonakshi Sinha \tD. Kareena Kapoor", "\tA. US Open \tB. Australian Open \tC. Wimbledon \tD. French Open", "\tA. Firoz Tughlaq \tB. Alauddin Khilji \tC. Qutb-ud-din Aibak \tD. Bahlul Lodi", "\tA. Nigeria \tB. Kenya \tC. Ethiopia \tD. Liberia",  "\tA. Bachendri Pal \tB. Santosh Yadav \tC. Premlata Agrawal \tD. Sucheta Kandethankar", "\tA. Coronation Cinematograph \tB. Olympia theatre \tC. Maratha Mandir \tD. Edward Theatre",  "\tA. Sarojini Naidu \tB. Vijay laxmi Pandit \tC. Laxmi Sehgal \tD. Hansa Mehta"]

ff_option_list = ["\n:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::", "\t\tB. Intikhaab\tC. Inquilab",  "\t\tB. Caught and Bowled\t\tD. Stumping", "\tA. Prof C N R Rao\t\tD. Dr K Radhakrishnan", "\tA. DM\tCP\tC. DSP", "\tA. Syed Ahmad Khan\t\tD. Dr Zakir Hussain", "\tA. Nilgiris \tB. Aravalli ", "\tA. Vidya Balan  \tD. Kareena Kapoor", "\t\tB. Australian Open \tC. Wimbledon", "\t\tC. Qutb-ud-din Aibak \tD. Bahlul Lodi", "\tC. Ethiopia \tD. Liberia",  "\tA. Bachendri Pal \tC. Premlata Agrawal ", "\tA. Coronation Cinematograph \tC. Maratha Mandir ",  "\tB. Vijay laxmi Pandit \tD. Hansa Mehta"]

ans_case1 = ['0','c','d','a','a','a','b','d','b','c','d','c','a','d']
ans_case2 = ['0','C','D','A','A','A','B','D','B','C','D','C','A','D']
ans_case3 = ['a', 'b', 'c', 'd', 'A', 'B', 'C', 'D']

prize = [0,10000,20000,40000,80000,160000,320000,640000,1250000,2500000,5000000,10000000,30000000]

quotes = ["Bhut Khub, Sahi jawab, Ab aap Jit chuke ho Rs.", "Awesome, You won Rs.", "Congrats ! Right Answer. Now you reach no Rs.", "Nice Played, You won Rs. ", "Shandar! Isi ke sath aap jit gye ho Rs.", """ Wow!!!!! You are now the owner of Rs. 5 Crore, You played incredibly. Everyone who is present here definiatly enjoyed your journey of this game. We wish for your bright future."""]
